<a href="https://colab.research.google.com/github/cfcarmem/Especialista_IA_Alura_102026/blob/main/colab_conecta_python_gemini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Criamos a chave API gemini no google ai studio https://aistudio.google.com/app/api-keys e adicionamos em Secrets. Em seguid guardamos na variável de ambiente  na maquina e tem que ter o nome GOOGLE_API_KEY

In [ ]:
import os  #biblioteca para guardar a chave em variável de ambiente no python
from google import genai #importando o gemini

from google.colab import userdata
os.environ["GOOGLE_API_KEY"]=userdata.get('gemini_api')

#vamos conectar o pytho no gemini

client = genai.Client()

#exemplo enviando a pergunta para a IA gemini
resposta=client.models.generate_content(model="gemini-3.5-flash-lite",contents="O que é sistema embarcado?")
print(resposta.text)

Um **sistema embarcado** (ou embutido) é um sistema computacional dedicado que realiza uma função específica dentro de um sistema mecânico ou elétrico maior.

Diferente de um computador de uso geral (como um notebook ou smartphone), que executa milhares de programas diferentes conforme a vontade do usuário, o sistema embarcado é projetado para **tarefas específicas**, geralmente com restrições de tempo real, consumo de energia e espaço físico.

### Características Principais
1. **Propósito Único:** Ele faz uma coisa (ou um grupo restrito de coisas) muito bem.
2. **Hardware e Software Integrados:** O software (muitas vezes chamado de *firmware*) é gravado diretamente no hardware do dispositivo.
3. **Recursos Limitados:** Costumam ter menos memória, processadores menos potentes e menor capacidade de armazenamento do que um computador convencional, pois precisam ser baratos e eficientes.
4. **Funcionamento em Tempo Real (Muitas vezes):** Precisam responder a estímulos externos de forma imediata e previsível (ex: os freios ABS de um carro).
5. **Autonomia:** Geralmente funcionam sem intervenção humana direta e sem periféricos tradicionais como teclado, mouse ou monitor.

### Exemplos no Dia a Dia
Você provavelmente usa dezenas de sistemas embarcados todos os dias sem perceber. Alguns exemplos:
* **Eletrodomésticos:** Micro-ondas, máquinas de lavar roupa, geladeiras inteligentes.
* **Automóveis:** Injeção eletrônica, centrais multimídia, controle de estabilidade, airbags.
* **Entretenimento:** Videogames, Smart TVs, controles remotos.
* **Saúde:** marca-passos cardíacos, aparelhos de pressão digital, equipamentos de ressonância magnética.
* **Indústria:** Robôs de linha de montagem, sensores IoT (Internet das Coisas).

### Do que é feito?
* **Hardware:** Geralmente construído em torno de um **Microcontrolador** (MCU) ou SoC (*System on a Chip*), que reúne o processador, memória e entradas/saídas em um único chip (como chips da Arduino, ESP32, Raspberry Pi Pico, etc.).
* **Software:** Pode rodar "bare-metal" (código direto no hardware, sem sistema operacional) ou com Sistemas Operacionais de Tempo Real (RTOS) para gerenciar tarefas mais complexas.

CONCEITOS DE **LOOP**

In [ ]:
n=1
letra ='*'
while n <=10:
  print(n * letra)
  n=n+1

CONECTANDO  AO GEMINI **CHATBOT**

In [ ]:
instancia = client.chats.create(model="gemini-3.5-flash-lite")
resposta = instancia.send_message("O que é torque? Me explique de forma sucinta.")
print(resposta.text)

In [ ]:
instancia.get_history()

**CHATBOT COM PERGUNTA E RESPOSTA**
-pegar prompt do usuario

In [ ]:
prompt = input("Digite a sua pergunta")
#vamos usar laços de repetição
while prompt != 'fim':
  resposta = instancia.send_message(prompt)
  print(resposta.text)
  print("/n")   #quebra de linha
  prompt = input("Digite a sua pergunta")

**EXPLORANDO ESTRUTURA DE DADOS EM PYTHON**

*   Listas

In [ ]:
#LISTA
lista_de_nomes =["Maria Alves", "João Da Silva", "Luis Ignacio Lula da Silva"]

#acessar elementos da lista. A lista começa com zero. Vamos pegar o terceiro
terceiro_elemento = lista_de_nomes[2]
print(terceiro_elemento)

*   Loop numa lista

In [ ]:
lista_numeros =[1,2,4,5,6,8,10]
list.append(lista_numeros,12)
list.insert(lista_numeros,2,13)
print(lista_numeros)

#ver quantas vezes elemento aparece na lista
lista2 = list.count(lista_numeros,20)

#percorrer a lista, mas os cinco primeiros
n=0
while n <= 5:
  print(lista_numeros[n])
  if n == 2:
    lista_numeros.remove(n)
  n = n+1
print(lista_numeros)

#mostrar a lista  posiçõ 1 até n-1 (o último valor depois do : é excludente. Ao invés de 3, ele vai trazer 2)
print(lista_numeros[1:3+1])

#A partir do 1
print(lista_numeros[1:])

#até a posição 3 (3-1.  de 0 a 2)
print(lista_numeros[:3])

#list.extend mais de um elemento
lista_numeros.extend([52,53,56])
print(lista_numeros)

*   **Função len**

In [ ]:
tamanho_lista = len(lista_numeros)
print(tamanho_lista)

**Função list.extend adiciona uma lista na lista**

In [ ]:
lista2 = [66,78]
lista_numeros.extend(lista2)

print(lista_numeros)


#posso usar o list.append. Mas vai adicionar uma lista na lista e não os elementos
lista_numeros.append([101,107])

print(lista_numeros)

lista_numeros[4]

#com list de string, consigo percorrer cada elemento do segundo nome.
nome = lista_de_nomes[2]
n=0
while n<len(nome):
  print(nome[n])
  n = n+1

**Remover elemento da lista**

In [ ]:
#remover o último elemento somente (pop)


#lista_numeros.remove(4)
print(lista_numeros)


lista_numeros.pop()
print(lista_numeros)


* **Dicionários**

In [ ]:
dict_de_nomes_e_media = {}
dict_de_nomes_e_media = { "Maria Silva": 8.9, "João Santos": 7.5, "Ana Oliveira": 4.2, "Pedro Costa": 1.4, "Juliana Pereira": 9.5 }

dict_de_nomes_e_media.get("Maria Silva")

#remove um elemento do dicionário e não o último como na lista
dict_de_nomes_e_media.pop("Juliana Pereira")

#mostra os itens da lista
dict_de_nomes_e_media.items()

#mostra somente  chave
dict_de_nomes_e_media.keys()

#mostra somente o valor, sem a chave
dict_de_nomes_e_media.values()

Criando estrutur de dados

In [ ]:
dict_desafio = {}

#vamos ter  a lista e dentro da lista um dicion´rio
dict_desafio = [

    {"nome": "Maria Silva", "média": 8.9}

]

dict_desafio = [

    {"nome": "Maria Silva", "média": 8.9},

    {"nome": "João Santos", "média": 7.5},

    {"nome": "Ana Oliveira", "média": 4.2},

    {"nome": "Pedro Costa", "média": 1.4}

]

#mostrar a posição zero
dict_desafio[0]

#mostrar somente a média da posição zero
dict_desafio[0]["média"]

Acessar elementos do fim da lista

In [ ]:
nomes = ['Maria', 'João', 'Ana', 'Pedro', 'Juliana']

print(nomes[-1])  # Exibe 'Juliana'
print(nomes[-2])  # Exibe 'Pedro'


#usando operaçao slicing

# Exemplo de slicing com índice negativo
ultimos_tres = nomes[-3:]
print(ultimos_tres)  # Exibe ['Ana', 'Pedro', 'Juliana']

* Loop for

In [ ]:
for elemento in dict_desafio:
    print(elemento)

In [ ]:
    #for e RANGE (faixa de elementos. Do element tal ao tal)
    for n in range(5) :
      # é como fazer lista_de_nomes[0:4]
      #aqui é 0 até 4
      print(n)

In [ ]:
for n in range(2,7):
  #começa no 2 e o 7 não incluido
  print(n)

In [ ]:
for n in range(2,7,2):
  #começa 2 até menor que sete, pulando de 2 em 2
  print(n)

In [ ]:
pessoa ={
    "nome":"Carmem", "idade":"90", "altura":"1.90"
}



print(pessoa.items())

In [ ]:
for chave in pessoa:
  #imprime somente as chaves
  print(chave)

In [ ]:
pessoa =[
    {
      "nome":"Carmem", "idade":"90", "altura":"1.90"
    },
     {
      "nome":"Evaldo", "idade":"90", "altura":"1.90"
    }

]

for p in pessoa:
    for chave, valor in p.items():
        print(f"{chave}: {valor}")
    print("---")

In [ ]:
for n in range(11):
  if n % 2 == 0:
    print(f"O numero {n} é par.")

In [ ]:
#Funções em Python
texto1 = "Ana Silva"
texto2 = "cARlos Souza"
texto3 = "Beatriz sAntos"
texto4 = "Daniel Oliveira"
texto5 = "Eduarda Lima"

In [ ]:
#criando function em python

def escreve_texto_corretamente(texto):
  retorno = texto.strip().upper().replace('  ',' ')
  lista = retorno.split()
  junta = " ".join(lista)
  return retorno

In [ ]:
escreve_texto_corretamente(texto1)

In [ ]:
#Simplificação de funções
salas_de_aula = ["Sala 1", "Sala 2", "Sala 3"]

In [ ]:
def escreve_texto_corretamente(texto):
    nome_final = " ".join(texto.upper().split())
    return nome_final

In [ ]:
import random

def aloca_alunos_em_salas(aluno, lista_de_salas):
  #random.choice - escolha aleatória
  sala_do_aluno = random.choice(lista_de_salas)

  dict_aluno = {
    "nome": aluno,
    "sala": sala_do_aluno
  }
  print(dict_aluno)

In [ ]:

aloca_alunos_em_salas(escreve_texto_corretamente(texto1), salas_de_aula)

In [ ]:
#DESAFIO
corpos_emails = [
    """
    Olá, equipe!

    Gostaria de informar que a reunião de planejamento para o próximo trimestre foi remarcada para a próxima sexta-feira, às 10h.
    Por favor, confirmem sua presença.

    Atenciosamente,
    João Silva
    """,
    """
    Prezados clientes,

    Nossa plataforma passará por uma atualização de sistema na madrugada de sábado para domingo.
    O serviço poderá ficar indisponível por algumas horas. Pedimos desculpas por qualquer transtorno.

    Atenciosamente,
    Equipe de Suporte
    """,
    """
    Oi, Maria!

    Tudo bem? Estou te escrevendo para saber se você recebeu o relatório que te enviei ontem.
    Precisamos fechar a análise até o final da semana. Me avise se precisar de algo.

    Abraços,
    Carlos
    """,
    """
    Caros colaboradores,

    Lembramos que o prazo para a entrega dos holerites de dezembro se encerra na próxima segunda-feira.
    Qualquer dúvida, por favor, entrem em contato com o departamento de RH.

    Obrigado,
    Recursos Humanos
    """,
    """
    Olá,

    Confirmamos o recebimento do seu pedido #12345. Ele já está em processamento e você receberá um novo email
    com o código de rastreamento assim que for enviado.

    Obrigado por comprar conosco!
    """,
    """
    Bom dia,

    Escrevo para formalizar o pedido de férias de 15 dias, com início previsto para o dia 20 de agosto.
    Aguardo a aprovação.

    Obrigado,
    André Costa
    """,
    """
    Olá, Fernando,

    Gostaria de agradecer a sua participação no nosso último webinar.
    Seu feedback foi muito importante para nós. Em anexo, segue o material completo apresentado.

    Atenciosamente,
    Time de Marketing
    """,
    """
    Prezado(a) [Nome do Cliente],

    A sua fatura mensal no valor de R$ [valor] referente aos serviços de [serviço] está disponível.
    Você pode acessá-la e realizar o pagamento através do nosso portal do cliente.

    Atenciosamente,
    Equipe Financeira
    """,
    """
    Oi, Ana!

    Que tal sairmos para almoçar na quarta-feira?
    Pensei naquele restaurante novo que abriu perto do escritório.
    Me avisa se você puder.

    Beijos,
    Lúcia
    """,
    """
    Prezados fornecedores,

    Gostaria de solicitar um orçamento detalhado para a compra de 500 unidades do produto X.
    Aguardamos o retorno o mais breve possível.

    Cordialmente,
    Departamento de Compras
    """,
    """
    Olá, Pedro,

    Recebi seu currículo e achei seu perfil bastante interessante para a vaga de Desenvolvedor Júnior.
    Gostaria de agendar uma entrevista para a próxima semana. Poderia nos informar sua disponibilidade?

    Obrigado,
    Recrutamento e Seleção
    """,
    """
    Bom dia,

    Estamos com problemas técnicos em nossa rede.
    Nossa equipe já está trabalhando para resolver a situação e normalizar o serviço o mais rápido possível.

    Agradecemos a compreensão.
    """,
    """
    Prezado Sr. Antônio,

    Escrevo para confirmar nossa reunião agendada para amanhã, às 14h, em sua sala.
    Estaremos discutindo a proposta de projeto que lhe enviamos.

    Atenciosamente,
    Mariana Fontes
    """,
    """
    Olá,

    Parabéns! Você acaba de ganhar 10% de desconto na sua próxima compra em nossa loja online.
    Use o cupom **DESCONTO10** no checkout.

    Aproveite!
    """,
    """
    Oi, galera!

    A festa de confraternização da empresa será no dia 15 de dezembro, a partir das 19h, no Salão de Eventos.
    Teremos música, comida e muita diversão! Não percam!

    Até lá,
    Comitê de Festas
    """,
    """
    Prezada Sra. Costa,

    Obrigado por entrar em contato. Seu pedido de cancelamento de assinatura foi processado.
    Você receberá uma confirmação separada em breve.

    Qualquer dúvida, estamos à disposição.
    """,
    """
    Boa tarde,

    Gostaria de saber se é possível adiar o prazo de entrega do projeto A para a próxima semana.
    Estamos com alguns contratempos e precisamos de mais tempo para garantir a qualidade final.

    Obrigado,
    Roberto Almeida
    """,
    """
    Olá, equipe de vendas,

    O relatório de desempenho do último mês foi liberado.
    Por favor, analisem os dados e me enviem seus comentários até o final da semana.

    Atenciosamente,
    Diretoria Comercial
    """,
    """
    Prezados pais e responsáveis,

    Lembramos que a reunião de pais será realizada nesta quinta-feira, às 19h, na quadra da escola.
    Sua presença é muito importante.

    Atenciosamente,
    Direção da Escola
    """,
    """
    Olá,

    Convidamos você para nosso próximo workshop sobre Inteligência Artificial, que acontecerá no dia 30 de setembro.
    As vagas são limitadas! Garanta a sua inscrição pelo link: [link para inscrição].

    Esperamos você!
    """,
]

In [ ]:
import os  #biblioteca para guardar a chave em variável de ambiente no python
from google import genai #importando o gemini

from google.colab import userdata
os.environ["GOOGLE_API_KEY"]=userdata.get('gemini_api')

#vamos conectar o pytho no gemini

client = genai.Client()

In [ ]:
def resumidor_de_emails(lista_de_emails):
    lista_de_resumos = []

    for numero, email in enumerate(lista_de_emails):
        resposta = client.models.generate_content(
            model="gemini-3.5-flash",
            contents=f"""Vou te mandar o corpo de um e-mail. Quero que você o resuma em apenas 1 linha,
                        passando o intuito daquele e-mail. Segue o e-mail: {email}"""
            )
        print(f"E-mail {numero + 1}: {resposta.text}")
        lista_de_resumos.append(f"E-mail {numero + 1}: {resposta.text}")
        print("-" * 50)

    return lista_de_resumos

In [ ]:
lista_resumos = resumidor_de_emails(corpos_emails)

In [ ]:
#IA openSource  - groq.com

In [ ]:
#tem que instalar o groq com -q (para não mostra nada)
!pip install -q groq

In [ ]:
os.environ["GROQ_API_KEY"]=userdata.get('groq_alura')

In [ ]:
#temperatura vai de 0 a 2(depende do modelo).  valor 0=menos criativo possível, 2=mais criativo possível.
#Temperatura baixa: favorece mais as opções com maior probabilidade.

#Temperatura alta: dá relativamente mais chance a opções menos prováveis.

#Temperatura zero: em configurações compatíveis, o modelo tende a escolher a opção

from groq import Groq

client = Groq()
completion = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content": "o que é torque\n"
      }
    ],
    temperature=1,
    max_completion_tokens=2048,
    top_p=1,
    reasoning_effort="medium",
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

#MANIPULAÇÃO DE ARQUIVOS - ESCREVENDO

In [ ]:
#eXPLORANDO A LEITURA E ESCRITA DE ARQUIVOS
#Parâmetros : w : write escreve no arquivo. Se o arquivo existir, ele apaga tudo que já existe e escreve de novo
# a : append : escreve a partir da últim linha. Não apaga

#aqui ele cria o arquivo txt com a lista.

with open("lista-de-resumos.txt", "w", encoding="utf-8") as arquivo:
  for resumo in lista_resumos:
    #.write escreve linh a linha no arquivo, dá para controlar melhor
    #.writeline  não precisa ficar dentro do for, ele escreve tudo de uma vez, não pula linha
    arquivo.write(resumo + "\n")


**MANIPULAÇÕ DE ARQUIVOS - LEITURA**

In [ ]:
nova_lista_arquivo_leitura = []
with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
  for linha in arquivo:
    nova_lista_arquivo_leitura.append(linha.strip())

nova_lista_arquivo_leitura

['E-mail 1: Solicitação de agendamento de reunião para alinhar as próximas etapas do projeto.',
 'E-mail 2: Solicitação de envio do relatório atualizado até o final do dia para dar continuidade à análise.',
 'E-mail 3: O e-mail tem o intuito de agradecer ao destinatário pela colaboração e parceria na conclusão de uma etapa da atividade.',
 'E-mail 4: O e-mail notifica o cliente sobre um pagamento pendente e solicita que ele verifique a situação.',
 'E-mail 5: Aviso de manutenção programada no sistema neste sábado, das 22h às 23h, com possível indisponibilidade temporária.']

In [ ]:
#com read
nova_lista_arquivo_leitura = []
with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
  conteudo = arquivo.read()
  nova_lista_arquivo_leitura.append(conteudo.strip())

nova_lista_arquivo_leitura

['E-mail 1: Solicitação de agendamento de reunião para alinhar as próximas etapas do projeto.\nE-mail 2: Solicitação de envio do relatório atualizado até o final do dia para dar continuidade à análise.\nE-mail 3: O e-mail tem o intuito de agradecer ao destinatário pela colaboração e parceria na conclusão de uma etapa da atividade.\nE-mail 4: O e-mail notifica o cliente sobre um pagamento pendente e solicita que ele verifique a situação.\nE-mail 5: Aviso de manutenção programada no sistema neste sábado, das 22h às 23h, com possível indisponibilidade temporária.']

In [ ]:
#com realine
nova_lista_arquivo_leitura2 = []
with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
  conteudo = arquivo.readline()
  nova_lista_arquivo_leitura2.append(conteudo.strip())

In [ ]:
nova_lista_arquivo_leitura2

In [ ]:
#com realines - não dá para usar o strip.  (melhor usar o for, tem mais controle)
nova_lista_arquivo_leitura3 = []
with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
  conteudo = arquivo.readlines()
  nova_lista_arquivo_leitura3.append(conteudo)


nova_lista_arquivo_leitura3

In [ ]:
#para o colab acessar o meu google drive
from google.colab import drive
drive.mount('/content/drive')

**PANDAS - E SUA IMPORTÂNCIA**    17-10-26

In [ ]:
import pandas as pd

In [ ]:
#csv = arquivo separado por virgula
#pandas lê varios formatos de arquivo

#este é o caminho do arquivo.
"/content/meu_csv.csv"


#nome da variável geralmente é df de data frame
df = pd.read_csv("/content/meu_csv.csv")

In [ ]:
#vamos mostrar o conteúdo do arquivo. É só imprimir o df
df

In [ ]:
#mostrar os cinco primeiros

df.head()

In [ ]:
#mostrar os dois primeiros
df.head(2)

In [ ]:
#os cinco ultimos
df.tail()

**DESAFIO**

1- criar um txt a partir de uma lista de perguntas vinda de uma lista python

2 - ler as perguntas do txt
3 - obter respostas de um LLM para cada pergunta
4 - salvar os resultados em um csv
5 - ler o csv usando PANDAS

In [ ]:
import csv
import pandas as pd
import os
from groq import Groq

In [ ]:
#1 - criando lista de perguntas no Pyton
lista_perguntas = [
    "O que é física quântica?",
    "O que é a dualidade onda-partícula?",
    "O que significa o princípio da incerteza de Heisenberg?",
    "O que é o entrelaçamento quântico?",
    "Qual é a diferença entre física clássica e física quântica?"
]

In [ ]:
#1 - criar o txt com as perguntas
with open("perguntas.txt", "w", encoding="utf-8") as arquivo:
  for pergunta in lista_perguntas:
    arquivo.write(pergunta + "\n")

In [ ]:
#2 - lendo as perguntas do txt
nova_lista_perguntas = []
with open("perguntas.txt", "r", encoding="utf-8") as arquivo:
  for linha in arquivo:
    nova_lista_perguntas.append(linha.strip())

nova_lista_perguntas

['O que é física quântica?',
 'O que é a dualidade onda-partícula?',
 'O que significa o princípio da incerteza de Heisenberg?',
 'O que é o entrelaçamento quântico?',
 'Qual é a diferença entre física clássica e física quântica?']

In [ ]:
#3 - obter respostas a partir de um LLM usando CSV para criar arquivo

#vamos usar groq. Já foi carregado acima

from groq import Groq

client2 = Groq()

def perguntado_LLM(pergunta, npergunta):
    completion = client2.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "user",
                "content": f"""Vou lhe mandar uma pergunta. Responder de forma sucinta, no maximo 5 linhas : {pergunta}"""
            }
        ],
        temperature=1,
        max_completion_tokens=2048,
        top_p=1,
        reasoning_effort="medium",
        stream=True,
        stop=None
    )


    with open("respostas.csv", "a", newline="", encoding="utf-8-sig") as arquivo:
          escritor = csv.writer(arquivo, delimiter=";")

          resposta_completa = ""

          for chunk in completion:
              resposta = chunk.choices[0].delta.content or ""
              # print(resposta, end="")
              resposta_completa += resposta

          escritor.writerow([f"{npergunta}-{pergunta}", resposta_completa])


    print(f"\nResposta da pergunta {npergunta} gravada no TXT.")

In [ ]:


client2 = Groq()

def perguntado_LLM_GROQ_PANDAS(pergunta, npergunta):
    completion = client2.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "user",
                "content": (
                    "Responda de forma sucinta, no máximo 5 linhas: "
                    + pergunta
                )
            }
        ],
        temperature=1,
        max_completion_tokens=2048,
        top_p=1,
        reasoning_effort="medium",
        stream=True
    )

    resposta_completa = ""

    for chunk in completion:
        resposta = chunk.choices[0].delta.content or ""
        resposta_completa += resposta

    # Criar DataFrame com a pergunta e a resposta
    df = pd.DataFrame([{
        "pergunta": f"{npergunta}-{pergunta}",
        "resposta": resposta_completa
    }])

    arquivo_csv = "respostas_groq_pandas.csv"

    escrever_cabecalho = (
        not os.path.exists(arquivo_csv)
        or os.path.getsize(arquivo_csv) == 0
    )

    # Gravar usando Pandas
    df.to_csv(
        arquivo_csv,
        mode="a",
        index=False,
        header=escrever_cabecalho,
        sep=";",
        encoding="utf-8",
        lineterminator="\n"
    )

    print(f"\nResposta da pergunta {npergunta} gravada no CSV.")

In [ ]:
#agora vamos dar o loop em nova_lista_perguntas.  CHAMANDO A LLM GROQ

linha = 0

for pergunta in nova_lista_perguntas:
    perguntado_LLM_GROQ_PANDAS(pergunta, linha)
    linha += 1

Resposta da pergunta 0 gravada no CSV.

Resposta da pergunta 1 gravada no CSV.

Resposta da pergunta 2 gravada no CSV.

Resposta da pergunta 3 gravada no CSV.

Resposta da pergunta 4 gravada no CSV.

In [ ]:
#criar um Dicionário para gravar as repostas da LLM Gemini

lista_respostas_gemini = []

In [ ]:
#Vou chamar a LLM do Gemini E GRAVAR csv usndo PANDAS


lista_respostas_gemini = []

def perguntado_LLM_gemini(pergunta, linhag):
    resposta = client.models.generate_content(
        model="gemini-3.5-flash",
        contents=f"""Vou lhe mandar uma pergunta.
        Responder de forma sucinta, no máximo 5 linhas: {pergunta}"""
    )

    lista_respostas_gemini.append({
        "pergunta": pergunta,
        "resposta": resposta.text
    })


# Gravar as respostas no CSV usando Pandas
df = pd.DataFrame(lista_respostas_gemini)

arquivo_csv = "respostas_gemini_pandas.csv"

if not df.empty:
    escrever_cabecalho = not os.path.exists(arquivo_csv) or os.path.getsize(arquivo_csv) == 0

    df.to_csv(
        arquivo_csv,
        mode="a",
        index=False,
        header=escrever_cabecalho,
        sep=";",
        encoding="utf-8-sig"
    )

    print("Respostas gravadas no CSV com sucesso!")

In [ ]:
#Vou chamar a LLM do Gemini e gravar usando a bibliotec csv (não a pandas)


lista_respostas_gemini = []

def perguntado_LLM_gemini(pergunta, linhag):
    resposta = client.models.generate_content(
        model="gemini-3.5-flash",
        contents=f"""Vou lhe mandar uma pergunta.
        Responder de forma sucinta, no máximo 5 linhas: {pergunta}"""
    )

    lista_respostas_gemini.append({
        "pergunta": pergunta,
        "resposta": resposta.text
    })


# Gravar as respostas no CSV
with open("respostas_gemini.csv", "a", newline="", encoding="utf-8-sig") as arquivo:
    escritor = csv.DictWriter(
        arquivo,
        fieldnames=["pergunta", "resposta"],
        delimiter=";"
    )

    # Escrever o cabeçalho somente se o arquivo estiver vazio
    if arquivo.tell() == 0:
        escritor.writeheader()

    escritor.writerows(lista_respostas_gemini)

In [ ]:
#Vampos dar o loop na list e chamar o gemini

linhag = 0

for pergunta in nova_lista_perguntas:
  perguntado_LLM_gemini(pergunta, linhag)
  linhag += 1

In [ ]:
#ultimo passo - Ler o csv com PANDAS

df = pd.read_csv("respostas_groq_pandas.csv", sep=";")
df

,pergunta,resposta
0,0-O que é física quântica?,A física quântica descreve o comportamento das...
1,1-O que é a dualidade onda-partícula?,A dualidade onda‑partícula descreve como partí...
2,2-O que significa o princípio da incerteza de ...,O princípio da incerteza de Heisenberg afirma ...
3,3-O que é o entrelaçamento quântico?,Entrelacamento quântico é a conexão profunda e...
4,4-Qual é a diferença entre física clássica e f...,A física clássica descreve sistemas macroscópi...

NameError: name 'dados' is not defined

5 - **MANIPULAÇÃO DE DADOS COM PANDAS**

In [5]:
#primeiras linhas do dataframe
df_produtos.head()

NameError: name 'df_produtos' is not defined

In [27]:
#ultimas linhas
df_produtos.tail()

45     True
46    False
47    False
48     True
49    False
Name: categoria, dtype: bool

In [30]:
#total de linhas
df_produtos.count(0)

produto               50
categoria             50
preço                 50
nota                  50
quantidade_vendida    50
dtype: int64

In [36]:
#exibindo todas as categorias cadastradas (distinct) com unique. Retorna array.
df_produtos['categoria'].unique()

array(['Casa e Decoração', 'Alimentos', 'Esportes', 'Vestuário',
       'Eletrônicos'], dtype=object)

In [35]:
#exibindo todas as categorias cadastrdas (distinct) com o set. Responta é um dicionário
set(df_produtos['categoria'])

{'Alimentos', 'Casa e Decoração', 'Eletrônicos', 'Esportes', 'Vestuário'}

In [34]:
#filtro simples

df_produtos[df_produtos["categoria"] == "Eletrônicos"]

       produto    categoria    preço  nota  quantidade_vendida
6   Smartphone  Eletrônicos   932.86   2.7                 117
14  Smartwatch  Eletrônicos   516.73   2.0                 105
30  Smartwatch  Eletrônicos  1003.47   3.2                 112
32  Carregador  Eletrônicos  2500.20   5.0                  69
45  Smartwatch  Eletrônicos  2692.75   1.8                   2
48    Notebook  Eletrônicos  2999.86   4.6                 125

In [37]:
#filtragem por Nota
df_produtos[df_produtos["nota"] < 2.0]

            produto         categoria    preço  nota  quantidade_vendida
2    Tapete de Yoga          Esportes   576.03   1.2                 100
4           Espelho  Casa e Decoração  2480.20   1.6                 126
9         Chocolate         Alimentos  3116.18   1.3                 113
17        Luminária  Casa e Decoração  2880.96   1.1                  37
20         Almofada  Casa e Decoração   378.77   1.6                 114
21        Luminária  Casa e Decoração   122.98   1.3                  57
29  Bola de Futebol          Esportes    36.92   1.5                  66
33   Vaso de Planta  Casa e Decoração   680.18   1.7                 110
38   Corda de Pular          Esportes   748.99   1.5                  39
45       Smartwatch       Eletrônicos  2692.75   1.8                   2

In [38]:
#Dando um count
df_produtos.shape

(50, 5)

In [40]:
#Combinando filtros
df_produtos_filtro_avaliacao_menor_que_2 = df_produtos[df_produtos["nota"] < 2.0]
df_produtos_filtro_avaliacao_menor_que_2.shape

(10, 5)

In [42]:
#usando & (AND)
df_produtos[(df_produtos["categoria"] == "Eletrônicos") & (df_produtos["preço"] >= 350.0)].shape

(6, 5)

In [43]:
#METODOS LOC E ILOC
#iLoc - vamos pegar o produto pelo índice
df_produtos.iloc[15]

produto                         Tapete
categoria             Casa e Decoração
preço                           2133.8
nota                               3.6
quantidade_vendida                  45
Name: 15, dtype: object

In [ ]:
#iloc - intervalod de linhas
df_produtos.iloc[0:16]

In [44]:
#iloc - linha intermediaria entre 34 e 42

df_produtos.iloc[34:42]

            produto  categoria    preço  nota  quantidade_vendida
34  Garrafa Térmica   Esportes  1807.21   3.0                   3
35            Meias  Vestuário  1095.27   3.0                  33
36   Corda de Pular   Esportes  1473.67   2.2                 103
37      Calça Jeans  Vestuário   257.77   3.7                 118
38   Corda de Pular   Esportes   748.99   1.5                  39
39            Meias  Vestuário   517.62   2.3                  26
40   Corda de Pular   Esportes  2801.62   2.0                 104
41  Bola de Futebol   Esportes  1450.91   4.9                  61

In [ ]:
#iloc a partir da linha 43
df_produtos.iloc[43:]

In [ ]:
#AGORA O MÉTODO LOC  - para trabalhar com indice não numerico
df_produtos_com_indice = df_produtos.set_index("categoria")
display(df_produtos_com_indice)

In [49]:
#loc - setar a categoria como indice
df_produtos_com_indice = df_produtos.set_index("categoria")
display(df_produtos_com_indice)

                          produto    preço  nota  quantidade_vendida
categoria
Casa e Decoração           Tapete  1761.01   4.2                 103
Alimentos                  Azeite  2948.21   4.1                   4
Esportes           Tapete de Yoga   576.03   1.2                 100
Vestuário                   Tênis  1374.77   2.9                   1
Casa e Decoração          Espelho  2480.20   1.6                 126
Esportes           Tapete de Yoga  1129.33   2.6                 111
Eletrônicos            Smartphone   932.86   2.7                 117
Alimentos                  Azeite   824.77   2.5                 124
Casa e Decoração   Vaso de Planta   956.66   2.6                 121
Alimentos               Chocolate  3116.18   1.3                 113
Alimentos                  Azeite  1850.58   2.3                 104
Esportes          Bola de Futebol   771.21   3.5                  34
Alimentos               Chocolate  3187.37   4.6                  25
Casa e Decoração   Vaso de Planta  1878.25   2.9                 129
Eletrônicos            Smartwatch   516.73   2.0                 105
Casa e Decoração           Tapete  2133.80   3.6                  45
Casa e Decoração         Almofada   470.49   2.0                 114
Casa e Decoração        Luminária  2880.96   1.1                  37
Casa e Decoração           Tapete  3421.33   3.0                  56
Casa e Decoração           Tapete    82.02   2.1                   3
Casa e Decoração         Almofada   378.77   1.6                 114
Casa e Decoração        Luminária   122.98   1.3                  57
Alimentos                    Café   797.42   2.2                  68
Casa e Decoração        Luminária  2501.24   3.6                 116
Esportes          Garrafa Térmica  1651.18   2.3                 100
Casa e Decoração           Tapete  2369.26   2.2                  47
Alimentos                    Café   313.62   4.8                  60
Alimentos                    Café  2307.74   3.5                   2
Alimentos                    Café  1643.66   2.0                 116
Esportes          Bola de Futebol    36.92   1.5                  66
Eletrônicos            Smartwatch  1003.47   3.2                 112
Alimentos               Chocolate   286.85   3.8                  38
Eletrônicos            Carregador  2500.20   5.0                  69
Casa e Decoração   Vaso de Planta   680.18   1.7                 110
Esportes          Garrafa Térmica  1807.21   3.0                   3
Vestuário                   Meias  1095.27   3.0                  33
Esportes           Corda de Pular  1473.67   2.2                 103
Vestuário             Calça Jeans   257.77   3.7                 118
Esportes           Corda de Pular   748.99   1.5                  39
Vestuário                   Meias   517.62   2.3                  26
Esportes           Corda de Pular  2801.62   2.0                 104
Esportes          Bola de Futebol  1450.91   4.9                  61
Alimentos                  Feijão  2889.83   3.9                  66
Alimentos                   Arroz  1695.13   4.0                  36
Vestuário                   Meias  3366.25   4.0                  10
Eletrônicos            Smartwatch  2692.75   1.8                   2
Esportes          Bola de Futebol  2888.70   2.4                  20
Esportes                 Halteres  2030.39   3.1                 149
Eletrônicos              Notebook  2999.86   4.6                 125
Alimentos                   Arroz  2912.24   3.0                 141

In [55]:
#após indexar o campo Categoria, vamos usar o loc para filtragem
df_produtos_com_indice.loc['Alimentos']

             produto    preço  nota  quantidade_vendida
categoria
Alimentos     Azeite  2948.21   4.1                   4
Alimentos     Azeite   824.77   2.5                 124
Alimentos  Chocolate  3116.18   1.3                 113
Alimentos     Azeite  1850.58   2.3                 104
Alimentos  Chocolate  3187.37   4.6                  25
Alimentos       Café   797.42   2.2                  68
Alimentos       Café   313.62   4.8                  60
Alimentos       Café  2307.74   3.5                   2
Alimentos       Café  1643.66   2.0                 116
Alimentos  Chocolate   286.85   3.8                  38
Alimentos     Feijão  2889.83   3.9                  66
Alimentos      Arroz  1695.13   4.0                  36
Alimentos      Arroz  2912.24   3.0                 141

In [2]:
#filtrar avançado. Select  categoria, produto, preco, not from ....

#AGORA O MÉTODO LOC  - para trabalhar com indice não numerico
df_produtos_com_indice = df_produtos.set_index("produto")
display(df_produtos_com_indice)

df_produtos_com_indice.loc[["Arroz", "Café"], ["preço", "nota"]]

NameError: name 'df_produtos' is not defined

In [66]:
#filtro por categoria
eletronicos = df_produtos_com_indice[df_produtos_com_indice["categoria"] == "Eletrônicos"]

In [67]:
#algumas colunas
df_produtos_com_indice.loc[eletronicos.index, ["preço", "nota"]]

              preço  nota
produto
Smartphone   932.86   2.7
Smartwatch   516.73   2.0
Smartwatch  1003.47   3.2
Smartwatch  2692.75   1.8
Smartwatch   516.73   2.0
Smartwatch  1003.47   3.2
Smartwatch  2692.75   1.8
Carregador  2500.20   5.0
Smartwatch   516.73   2.0
Smartwatch  1003.47   3.2
Smartwatch  2692.75   1.8
Notebook    2999.86   4.6

In [1]:
#ALTERANDO VALORES NO DATAFRAME  NO COM_INDICE AINDA

Notebook = df_produtos_com_indice[df_produtos_com_indice["Categoria"] == "Brinquedos"]

NameError: name 'df_produtos_com_indice' is not defined

In [7]:
# Exemplo simples: convertendo uma coluna para índice
import pandas as pd

dados = {'Produto': ['Produto A', 'Produto B', 'Produto C'],
         'Preço': [100, 150, 200],
         'Estoque': [30, 20, 50]}
df = pd.DataFrame(dados)

# Transformando a coluna 'Produto' em índice
df_indexado = df.set_index('Produto')
print(df_indexado)

           Preço  Estoque
Produto
Produto A    100       30
Produto B    150       20
Produto C    200       50